PSpecPlotter:
    output_dir: '/global/cscratch1/sd/anicola/DATA/HSCxACT/HSC/HSC_processed'
    output_run_dir: 'CovAna_NoiAna_MskSiriusSyst_ClTh_NoDpj'
#    saccdirs: ['GAMA15H_ceci', 'GAMA09H_ceci', 'WIDE12H_ceci', 'VVDS_ceci', 'XMM_ceci', 'HECTOMAP_ceci', 'AEGIS_ceci']
    saccdirs: ['GAMA15H_ceci', 'GAMA09H_ceci', 'WIDE12H_ceci', 'VVDS_ceci', 'XMM_ceci']
    noisesacc_filename: 'noi_bias_sim'
    output_plot_dir: 'plots'
    plot_fields: False
    tracers: ['gc_0', 'gc_1', 'gc_2', 'gc_3', 'wl_0', 'wl_1', 'wl_2', 'wl_3', 'kappa_0', 'y_0']
    ell_max_trc: [2000, 2000, 3000, 3000, 3000, 3000, 3000, 3000, 2000, 2000]
    fig_name: ['cls_wlxwl_all_data-vs-theor_ee.pdf',
               'cls_wlxwl_all_data-vs-theor_bb.pdf',
               'cls_gcxgc_all_data-vs-theor_00.pdf',
               'cls_gcxwl_all_data-vs-theor_0e.pdf',
               'cls_gcxwl_all_data-vs-theor_0b.pdf',
               'cls_gcxy_all_data-vs-theor_00.pdf',
               'cls_gcxkappa_all_data-vs-theor_00.pdf',
               'cls_kappaxwl_all_data-vs-theor_0e.pdf',
               'cls_kappaxwl_all_data-vs-theor_0b.pdf',
               'cls_yxwl_all_data-vs-theor_0e.pdf',
               'cls_yxwl_all_data-vs-theor_0b.pdf']
    plot_tracers: [['wl_0', 'wl_1', 'wl_2', 'wl_3'],
                   ['wl_0', 'wl_1', 'wl_2', 'wl_3'],
                   ['gc_0', 'gc_1', 'gc_2', 'gc_3'],
                   ['gc_0', 'gc_1', 'gc_2', 'gc_3', 'wl_0', 'wl_1', 'wl_2', 'wl_3'],
                   ['gc_0', 'gc_1', 'gc_2', 'gc_3', 'wl_0', 'wl_1', 'wl_2', 'wl_3'],
                   ['gc_0', 'gc_1', 'gc_2', 'gc_3', 'y_0'],
                   ['gc_0', 'gc_1', 'gc_2', 'gc_3', 'kappa_0'],
                   ['kappa_0', 'wl_0', 'wl_1', 'wl_2', 'wl_3'],
                   ['kappa_0', 'wl_0', 'wl_1', 'wl_2', 'wl_3'],
                   ['y_0', 'wl_0', 'wl_1', 'wl_2', 'wl_3'],
                   ['y_0', 'wl_0', 'wl_1', 'wl_2', 'wl_3']]
    plot_comb: ['all', 'all', 'all', 'cross', 'cross', 'cross', 'cross', 'cross', 'cross', 'cross', 'cross']
    cl_type: ['cl_ee', 'cl_bb', 'cl_00', 'cl_0e', 'cl_0b', 'cl_00', 'cl_00', 'cl_0e', 'cl_0b', 'cl_0e', 'cl_0b']
    plot_errors: True
    plot_theory: True
    weightpow: [-1, -1, 1.3, 1, 1, 1, 1, 1, 1, 1, 1]
    logscale_x: [True, True, True, True, True, True, True, True, True, True, True]
    logscale_y: [True, True, False, False, False, False, False, False, False, False, False]
    theory:
        hmparams:
            massdef: 'M200c'
            pprof: 'Battaglia'
            bhydro: 0.2
