PSpecPlotter:
    output_dir: '/global/cscratch1/sd/anicola/DATA/HSCxACT/HSC/HSC_processed'
    output_run_dir: 'CovAna_NoiAna_MskSiriusSyst_ClData_NoDpj'
    # saccdirs: ['GAMA15H_ceci', 'GAMA09H_ceci', 'WIDE12H_ceci', 'VVDS_ceci', 'XMM_ceci', 'HECTOMAP_ceci', 'AEGIS_ceci']
    # saccdirs: ['GAMA15H_ceci', 'GAMA09H_ceci', 'WIDE12H_ceci', 'VVDS_ceci', 'XMM_ceci']
    saccdirs: ['GAMA15H_ceci', 'WIDE12H_ceci', 'XMM_ceci']
    noisesacc_filename: NONE
    # noisesacc_filename: 'noi_bias_sim'
    output_plot_dir: 'plots'
    tracers: ['gc_0', 'gc_1', 'gc_2', 'gc_3', 'wl_0', 'wl_1', 'wl_2', 'wl_3', 'kappa_0', 'y_0']
    ell_max_trc: [2000, 2000, 3000, 3000, 3000, 3000, 3000, 3000, 2000, 2000]
    fig_name: 'cls_kappaxwl_all_0e_test.pdf'
    # plot_tracers: ['gc_0', 'gc_1', 'gc_2', 'gc_3', 'wl_0', 'wl_1', 'wl_2', 'wl_3']
    # plot_tracers: ['wl_0', 'wl_1', 'wl_2', 'wl_3']
    plot_tracers: ['kappa_0', 'wl_0', 'wl_1', 'wl_2', 'wl_3']
    # plot_tracers: ['gc_0', 'gc_1', 'gc_2', 'gc_3', 'y_0']
    plot_comb: 'cross'
    cl_type: 'cl_0e'
    plot_errors: False
    plot_theory: True
    weightpow: 1
    logscale_x: True
    logscale_y: False
    theory:
        hmparams:
            massdef: 'M200c'
            pprof: 'Battaglia'
            bhydro: 0.2
