global:
  depth_cut: 24.5
  mapping:
    res: 0.00833333333333
    pad: 0.2
    res_bo: 0.003
    projection: CAR
  mask_type: sirius
  band: i
  mask_thr: 0.5
  shearrot: noflip
  sys_collapse_type: average
  pz_code: ephor_ab
  pz_mark: best
  pz_bins: [0.3, 0.6, 0.9, 1.2, 1.5]
  plots_dir: /global/cscratch1/sd/damonge/GSKY/outputs/GAMA09H_ceci/plots

ReduceCat:
  min_snr: 10.
  depth_method: fluxerr

SystMapper:
  ccd_drop: [9]

COSMOSWeight:
  n_neighbors: 20

GalMapper:
  nz_bin_num: 100
  nz_bin_max: 4.0

ShearMapper:
  nz_bin_num: 100
  nz_bin_max: 4.0

#PowerSpecter:
#  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
#  gaus_covar_type: analytic
#  noise_bias_type: analytic
#  guess_spectrum: /global/homes/d/damonge/LSST/LSS_HSC/HyperSupremeStructure-HSC-LSS/hsc_lss_params/cls_guess_i24p5.txt
#  mask_systematics: True
#  oc_dpj_list: [airmass,seeing,sigma_sky]
#  oc_all_bands: True
#  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClFit_Dpj0_DpjBands1

PowerSpecter:
  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
  noise_bias_type: analytic
  guess_spectrum: NONE
  mask_systematics: False
  oc_dpj_list: []
  oc_all_bands: True
  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClThCpld_NoDpj

MockGen:
    tracers: ['wl_0', 'wl_1', 'wl_2', 'wl_3']
    probes: ['gamma', 'gamma', 'gamma', 'gamma']
    spins: [2, 2, 2, 2]
    nrealiz: 1000
    #path2cls: ['../HSC/data/cls_deltagxdeltag_dist=HSC-binned-phot-z.txt', '../HSC/data/cls_gammaxdeltag_dist=HSC-binned-phot-z.txt', '../HSC/data/cls_gammaxgamma_dist=HSC-binned-phot-z.txt']
    path2theorycls: NONE
    ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
    pixwindow: 0
    nell_theor: 5000
    noisemodel: data
    posfromshearcat: 1
    ntomo_bins: [0, 1, 2, 3]
    output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClData_NoDpj

GuessSpecter:
  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClThCpld_NoDpj_FourierCosmicShear
  cpl_cl: True
  ellmax: 30000
  hmparams:
    corr_halo_mod: True
    use_hm_matter: False
    massdef: 'M200c'
    pprof: 'Battaglia'
    HODmod: 'zevol'
    mmin: 12.02
    mminp: -1.3
    m0: 6.6
    m0p: -1.4
    m1: 13.27
    m1p: -0.3
    bhydro: 0.2
#    zshift_bin0: -0.0117
#    m_bin0: -0.00339
#    zshift_bin1: -0.00228
#    m_bin1: 0.000482
#    zshift_bin2: 0.02
#    m_bin2: 0.00112
#    zshift_bin3: -0.00706
#    m_bin3: 0.00348

  cosmo:
    Omega_b: 0.0493
    Omega_k: 0.0
    sigma8: 0.8111
    h: 0.6736
    n_s: 0.9649
    Omega_c: 0.264
    w0: -1.
    wa: 0.

CovGauss:
  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
  gaus_covar_type: analytic
  guess_spectrum: /global/cscratch1/sd/anicola/DATA/HSCxACT/HSC/HSC_processed/GAMA09H_ceci/CovAna_NoiAna_MskSiriusSyst_ClThCpld_NoDpj_FourierCosmicShear/guess_spectra_cpld.sacc
#  guess_spectrum: NONE
  mask_systematics: False
  oc_dpj_list: []
  oc_all_bands: True
  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClThCpld_NoDpj_FourierCosmicShear


CwspCalc:
  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
  mask_systematics: False
  oc_dpj_list: []
  oc_all_bands: True
  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClData_NoDpj