 GuessSpecter:
    output_run_dir: 'CovAna_NoiAna_MskSiriusSyst_ClThIt_NoDpj'
    noisesacc_filename: 'noi_bias_comb'
    #  noisesacc_filename: 'NONE'
    saccdirs: ['GAMA15H_ceci', 'GAMA09H_ceci', 'WIDE12H_ceci', 'VVDS_ceci', 'XMM_ceci']
    tracers: ['gc_0', 'gc_1', 'gc_2', 'gc_3', 'kappa_0', 'y_0', 'wl_0', 'wl_1', 'wl_2', 'wl_3']
    dcpl_cl: True
    ellmax: 30000
    hmparams:
        corr_halo_mod: True
        massdef: 'M500c'
        pprof: 'Arnaud'
        mmin: 11.28
        mminp: 2.02
        m0: 9.65
        m0p: -0.90
        m1: 12.85
        m1p: 2.98
        bhydro: 0.49
        zshift_bin0: 0.09
        zshift_bin1: 0.11
        zshift_bin2: 0.17
        zshift_bin3: 0.19
        zwidth_bin0: 0.17
        zwidth_bin1: 0.14
        zwidth_bin2: 0.09
        zwidth_bin3: 0.07
    cosmo:
        sigma8: 0.92
        Omega_c: 0.14
        Omega_b: 0.0493
        Omega_k: 0.0
        h: 0.6736
        n_s: 0.9649
        w0: -1.
        wa: 0.