LikeMinimizer:
    output_dir: '/global/cscratch1/sd/anicola/DATA/HSCxACT/HSC/HSC_processed'
    output_run_dir: 'CovAna_NoiAna_MskSiriusSyst_ClTh_NoDpj'
    saccdirs: ['GAMA15H_ceci', 'GAMA09H_ceci', 'WIDE12H_ceci', 'VVDS_ceci', 'XMM_ceci']
#    noisesacc_filename: NONE
    noisesacc_filename: 'noi_bias_comb'
    tracers: ['gc_0', 'gc_1', 'gc_2', 'gc_3', 'wl_0', 'wl_1', 'wl_2', 'wl_3', 'kappa_0', 'y_0']
#    ells: [  150.,   250.,   350.,   500.,   700.,   900.,  1200.,  1600.,
#             2000.,  2600.,  3400.,  4200.,  5400.,  7000.,  8600., 11000.,
#             14200.]
    ells: NONE
    ell_max_trc: [2000, 2000, 3000, 3000, 3000, 3000, 3000, 3000, 2000, 2000]
    param_keys: ['mmin', 'mminp', 'm0', 'm0p', 'm1', 'm1p', 'bhydro']
    theory:
        hmparams:
            massdef: 'M500c'
            pprof: 'Arnaud'
            bhydro: 0.2
            HODmod: 'zevol'
        cosmo:
            Omega_b: 0.0493
            Omega_k: 0.0
            sigma8: 0.8111
            h: 0.6736
            n_s: 0.9649
            Omega_c: 0.264
            w0: -1.
            wa: 0.
    minimizer:
        method: 'Powell'
        maxiter: 5000
        ftol: 1e-4
        x0: [12.02, -1.34, 6.6, -1.43, 13.27, -0.323, 0.2]
        bounds: [[10., 14.], [-4., 2.], [4., 8.], [-4., 2.], [11., 15.], [-4., 2.], [0.1, 0.5]]
#        bounds: None
