global:
  depth_cut: 24.5
  mapping:
    wcs: /global/cscratch1/sd/damonge/GSKY/ACT_data/mask_kappa_boss.fits
    res: 0.00833333333333
    pad: 0.2
    res_bo: 0.003
    projection: CAR
  mask_type: sirius
  band: i
  mask_thr: 0.5
  shearrot: noflip
  sys_collapse_type: average
  pz_code: ephor_ab
  pz_mark: best
  pz_bins: [0.3, 0.6, 0.9, 1.2, 1.5]
  plots_dir: /global/cscratch1/sd/damonge/GSKY/outputs/WIDE12H_ceci/plots

ReduceCat:
  min_snr: 10.
  depth_method: fluxerr

SystMapper:
  ccd_drop: [9]

COSMOSWeight:
  n_neighbors: 20

GalMapper:
  nz_bin_num: 100
  nz_bin_max: 4.0

ShearMapper:
  nz_bin_num: 100
  nz_bin_max: 4.0

ACTMapper:
  act_inputs:
    - ['y',
       '/global/cscratch1/sd/damonge/GSKY/ACT_data/y_boss.fits',
       '/global/cscratch1/sd/damonge/GSKY/ACT_data/mask_y_boss.fits']
    - ['kappa',
       '/global/cscratch1/sd/damonge/GSKY/ACT_data/kappa_boss.fits',
       '/global/cscratch1/sd/damonge/GSKY/ACT_data/mask_kappa_boss.fits']

#PowerSpecter:
#  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
#  gaus_covar_type: analytic
#  noise_bias_type: analytic
#  guess_spectrum: /global/homes/d/damonge/LSST/LSS_HSC/HyperSupremeStructure-HSC-LSS/hsc_lss_params/cls_guess_i24p5.txt
#  mask_systematics: True
#  oc_dpj_list: [airmass,seeing,sigma_sky]
#  oc_all_bands: True
#  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClFit_Dpj0_DpjBands1

PowerSpecter:
  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
  noise_bias_type: analytic
  guess_spectrum: NONE
  mask_systematics: False
  oc_dpj_list: []
  oc_all_bands: True
  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClThCpld_NoDpj

MockGen:
  tracers: ['gc_0', 'gc_1', 'gc_2', 'gc_3', 'kappa_0', 'y_0', 'wl_0', 'wl_1', 'wl_2', 'wl_3']
  probes: ['galaxy_density', 'galaxy_density', 'galaxy_density', 'galaxy_density', 'cmb_convergence', 'cmb_tSZ',
           'galaxy_shear', 'galaxy_shear', 'galaxy_shear', 'galaxy_shear']
  spins: [0, 0, 0, 0, 0, 0, 2, 2, 2, 2]
  nrealiz: 1000
  theory_sacc: '/tigress/anicola/DATA/HSCxACT/HSC/HSC_processed/outputs/inputs/'\
  'CovAna_NoiAna_MskSiriusSyst_ClThIt_NoDpj/saccfile_noise-free_guess_spectra_lmax=3e4.sacc'
  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,
             3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
  pixwindow: 0
  nell_theor: 5000
  noisemodel: ['data', 'data', 'data', 'data', 'ps', 'ps', 'ps', 'ps', 'data', 'data', 'data', 'data']
  posfromshearcat: 1
  ntomo_bins: [0, 1, 2, 3, -1, -1, 0, 1, 2, 3]
  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClThIt_NoDpj

#MockGen:
#  tracers: ['wl_0']
#  probes: ['gamma']
#  spins: [2]
#  nrealiz: 1000
#  theory_sacc: '/tigress/anicola/DATA/HSCxACT/HSC/HSC_processed/outputs/inputs/CovAna_NoiAna_MskSiriusSyst_ClThIt_NoDpj/saccfile_noise-free_guess_spectra_lmax=3e4.sacc'
#  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
#  pixwindow: 0
#  nell_theor: 5000
#  noisemodel: data
#  posfromshearcat: 1
#  ntomo_bins: [0]
#  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClThIt_NoDpj

#MockGen:
#    tracers: ['wl_0', 'wl_1', 'wl_2', 'wl_3']
#    probes: ['gamma', 'gamma', 'gamma', 'gamma']
#    spins: [2, 2, 2, 2]
#    nrealiz: 1000
#    #path2cls: ['../HSC/data/cls_deltagxdeltag_dist=HSC-binned-phot-z.txt', '../HSC/data/cls_gammaxdeltag_dist=HSC-binned-phot-z.txt', '../HSC/data/cls_gammaxgamma_dist=HSC-binned-phot-z.txt']
#    path2theorycls: NONE
#    ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
#    pixwindow: 0
#    nell_theor: 5000
#    noisemodel: data
#    posfromshearcat: 1
#    ntomo_bins: [0, 1, 2, 3]
#    output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClData_NoDpj

CovGauss:
  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
  gaus_covar_type: analytic
  guess_spectrum: /global/cscratch1/sd/anicola/DATA/HSCxACT/HSC/HSC_processed/inputs/CovAna_NoiAna_MskSiriusSyst_ClThIt_NoDpj/saccfile_noise-free_guess_spectra.sacc
#  guess_spectrum: NONE
  mask_systematics: False
  oc_dpj_list: []
  oc_all_bands: True
  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClThIt_CSCovSim_NoDpj

CwspCalc:
  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
  mask_systematics: False
  oc_dpj_list: []
  oc_all_bands: True
  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClData_NoDpj
