global:
  depth_cut: 24.5
  mapping:
    wcs: /global/cscratch1/sd/damonge/GSKY/ACT_data/mask_kappa_deep56.fits
    res: 0.00833333333333
    pad: 0.2
    res_bo: 0.003
    projection: CAR
  mask_type: sirius
  band: i
  mask_thr: 0.5
  shearrot: flipqu
  sys_collapse_type: average
  pz_code: ephor_ab
  pz_mark: best
  pz_bins: [0.3, 0.6, 0.9, 1.2, 1.5]
  plots_dir: /global/cscratch1/sd/damonge/GSKY/outputs/XMM_ceci/plots

ReduceCat:
  min_snr: 10.
  depth_method: fluxerr

SystMapper:
  ccd_drop: [9]

COSMOSWeight:
  n_neighbors: 20

GalMapper:
  nz_bin_num: 100
  nz_bin_max: 4.0

ShearMapper:
  nz_bin_num: 100
  nz_bin_max: 4.0

ACTMapper:
  act_inputs:
    - ['y',
       '/global/cscratch1/sd/damonge/GSKY/ACT_data/y_deep56.fits',
       '/global/cscratch1/sd/damonge/GSKY/ACT_data/mask_y_deep56.fits']
    - ['kappa',
       '/global/cscratch1/sd/damonge/GSKY/ACT_data/kappa_deep56.fits',
       '/global/cscratch1/sd/damonge/GSKY/ACT_data/mask_kappa_deep56.fits']

#PowerSpecter:
#  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
#  gaus_covar_type: analytic
#  noise_bias_type: analytic
#  guess_spectrum: /global/homes/d/damonge/LSST/LSS_HSC/HyperSupremeStructure-HSC-LSS/hsc_lss_params/cls_guess_i24p5.txt
#  mask_systematics: True
#  oc_dpj_list: [airmass,seeing,sigma_sky]
#  oc_all_bands: True
#  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClFit_Dpj0_DpjBands1

PowerSpecter:
  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
  gaus_covar_type: analytic
  noise_bias_type: analytic
  guess_spectrum: NONE
  mask_systematics: False
  oc_dpj_list: []
  oc_all_bands: True
  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClData_NoDpj

CovGauss:
  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
  gaus_covar_type: analytic
  noise_bias_type: analytic
  guess_spectrum: NONE
  mask_systematics: False
  oc_dpj_list: []
  oc_all_bands: True
  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClData_NoDpj

CwspCalc:
  ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
  mask_systematics: False
  oc_dpj_list: []
  oc_all_bands: True
  output_run_dir: CovAna_NoiAna_MskSiriusSyst_ClData_NoDpj